# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50d1b85b1d5dcdb5178ab8681f55a22aca2ad3bef72074881b5376a3e8a543cd2b175da9a1baffbfa2f3fe04ff8e61a718aabe53dc826254fff2bcda01b7a9d6

test:
  secret_key_base: f0f138ea374991b778d2afc8487b344c99ff5f3de962d9593430a9d18c44d26a3d0f9fffcd53463dcd15e229dd31812d02f13851f9e7ecfe2e109bbc6c6a9dbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
